apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: appvm1
  namespace: nve-fleet
spec:
  targets:
    - clusterGroup: test-config1
      name: test-config1
  repo: https://github.com/pmacko86/fm-examples
  paths:
    - deployed2/applications/appvm1
