apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  name: rtp-dev
  namespace: allclusters
spec:
  selector:
    matchLabels:
      env: dev
      location: rtp

---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rtp-dev
  namespace: allclusters
spec:
  branch: main
  paths:
    - girish-cluster/configs/rtp-dev
  repo: https://github.com/pmacko86/fm-examples
  targets:
    - clusterGroup: rtp-dev
      name: rtp-dev
