apiVersion: nve.netapp.io/v1
kind: NVEVirtualMachine
metadata:
  annotations:
    annotation.nve.netapp.io/description: An example of another VM-based
      application. Updating just to see whether it works.
  name: inference-vm2
spec:
  template:
    spec:
      cpu: 4
      gpu:
        count: 2
        minModel: Tesla T4
      image:
        marketplace: nve-marketplace
        name: inference2
        version: "2.5"
      memory: 16GB
      network:
        - name: vnet-private
      storage:
        - cacheMode: writethrough
          capacity: 100GB
          mountPath: /data
