apiVersion: nve.netapp.io/v1
kind: NVENetworkSecurityGroup
metadata:
  name: macko-sg1
spec:
  rules:
    - direction: inbound
      ports: "*"
      protocol: tcp
    - direction: outbound
      ports: "*"
      protocol: tcp

---
apiVersion: nve.netapp.io/v1
kind: NVEVirtualNetwork
metadata:
  name: macko-vnet1
spec:
  cidr: 172.16.1.0/24
  mode: bridge
  securityGroups:
    - name: macko-sg1
  size: 32
  type: private

---
apiVersion: nve.netapp.io/v1
kind: NVEVirtualNetwork
metadata:
  name: macko-vnet2
spec:
  securityGroups:
    - name: macko-sg1
  type: private
  cidr: 172.16.2.0/24
  size: 32
  mode: bridge
