apiVersion: nve.netapp.io/v1
kind: NVEKubernetesCluster
metadata:
  name: kubernetes
spec:
  controlPlaneTemplate:
    spec:
      cpu: 4
      memory: 16GB
      storage:
        - cacheMode: writethrough
          capacity: 16GB
          mountPath: /data
  kubernetes:
    type: default
    version: 1.22.4
  replicas:
    onEvery: 1
  workerTemplate:
    spec:
      cpu: 4
      gpu:
        count: 2
        minModel: Tesla T4
      memory: 16GB
      storage:
        - cacheMode: writethrough
          capacity: 128GB
          mountPath: /data
