apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: redis
  namespace: allclusters
spec:
  branch: main
  paths:
    - girish-cluster/applications/redis
  repo: https://github.com/pmacko86/fm-examples
  targets:
    - clusterGroup: rtp-dev-guest
      name: rtp-dev-guest
